"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from django.utils.translation import gettext_lazy as _
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-*&6q$th5e7uw8_@t(iun8ayq6q!nm+hl7h42!$ocsfeh+v1nv-'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG = os.getenv("DJANGO_DEBUG", "0") == "1"
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret")
# DEBUG = os.environ.get("DEBUG", "False") == "True"
DEBUG = "True"

# ALLOWED_HOSTS = ["*"]

# ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if h.strip()]
# CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")]
raw_hosts = os.environ.get("ALLOWED_HOSTS", "").split(",")
ALLOWED_HOSTS = [h.strip() for h in raw_hosts if h.strip()]
CSRF_TRUSTED_ORIGINS = []
for h in ALLOWED_HOSTS:
    # пропускаем wildcard и локальные адреса
    if h == "*" or h in ("localhost", "127.0.0.1"):
        continue
    CSRF_TRUSTED_ORIGINS.append(f"https://{h}")
    CSRF_TRUSTED_ORIGINS.append(f"http://{h}")

# Если не задано явно — разрешим любой Host, чтобы health-check не падал
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'storages',

    # Third-party
    "rest_framework",
    "django_filters",
    "parler",

    # Project apps
    "users",
    "catalog",
    "cart",
    "orders",
    "payments",
    "cms",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]



ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "cart.context_processors.cart_info",
                "cart.context_processors.cart_header",
            ],
        },
    },
]



WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("POSTGRES_DB", "shopdb"),
#         "USER": os.getenv("POSTGRES_USER", "shopuser"),
#         "PASSWORD": os.getenv("POSTGRES_PASSWORD", "shopsecret"),
#         "HOST": os.getenv("POSTGRES_HOST", "db"),
#         "PORT": int(os.getenv("POSTGRES_PORT", "5432")),
#         "CONN_MAX_AGE": 60,
#     }
# }
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
    )
}

# Сессии и кэш в Redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HOST','redis')}:{os.getenv('REDIS_PORT','6379')}/1",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# I18N / L10N
LANGUAGE_CODE = "ka"  # по умолчанию грузинский
LANGUAGES = [
    ("ka", _("ქართული")),
    ("en", _("English")),
]
LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = os.getenv("TZ", "Asia/Tbilisi")
USE_I18N = True
USE_TZ = True

# Статика и медиа
STATIC_URL = "/static/"

# где collectstatic будет собирать файлы (на проде/тесте; в DEBUG можно не трогать)
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent.parent
STATIC_ROOT = BASE_DIR / "staticfiles"

# твоя пользовательская директория со статикой проекта (может быть пустой, но ДОЛЖНА существовать)
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# на всякий случай зафиксируем стандартные файндеры
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Пользовательская модель (создадим ниже)
AUTH_USER_MODEL = "users.User"

# DRF базовая конфигурация
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

# Parler (переводы модельных полей — подключим в нужных моделях позже)
PARLER_LANGUAGES = {
    None: (
        {"code": "ka"},
        {"code": "en"},
    ),
    "default": {
        "fallbacks": ["en"],
        "hide_untranslated": False,
    },
}

PAYMENTS = {
    "MOCKPAY_PUBLIC_URL": "/payments/mockpay/callback/",
    "MOCKPAY_WEBHOOK_SECRET": os.getenv("MOCKPAY_WEBHOOK_SECRET", "mockpay_test_secret_123"),
}

DEFAULT_FROM_EMAIL = "no-reply@izugdidi.example"
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")

CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST','redis')}:{os.getenv('REDIS_PORT','6379')}/2"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/users/account/orders/"

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_ACCESS_KEY_ID = os.environ.get("SPACES_KEY")
AWS_SECRET_ACCESS_KEY = os.environ.get("SPACES_SECRET")
AWS_STORAGE_BUCKET_NAME = os.environ.get("SPACES_BUCKET")
AWS_S3_ENDPOINT_URL = os.environ.get("SPACES_ENDPOINT")
AWS_S3_REGION_NAME = os.environ.get("SPACES_REGION", "ams3")
AWS_DEFAULT_ACL = "public-read"
AWS_QUERYSTRING_AUTH = False  # чистые ссылки без подписи

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = False

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# (Можно оставить HSTS — это на уровне браузера, не мешает probe)
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        # ← самое важное: ошибки запросов (500) идут сюда
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# чтобы исключения показывались в логах даже без DEBUG
DEBUG_PROPAGATE_EXCEPTIONS = True