# Generated by Django 5.2.7 on 2025-10-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('address', 'Доставка по адресу')], default='pickup', max_length=16),
        ),
    ]
